### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by alanyee** [devsecops/restacker#20]
I managed to install from source via
```
git clone https://github.com/devsecops/restacker.git
cd restacker/source
gem install bundler
bundle install
gem build restacker.gemspec
gem install restacker
```
But then I run into this problem when I try to run `restacker`
```
Traceback (most recent call last):
	5: from /usr/local/bin/restacker:23:in `<main>'
	4: from /usr/local/bin/restacker:23:in `load'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/restacker-1.0.0/bin/restacker:114:in `<top (required)>'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/restacker-1.0.0/lib/restacker_config.rb:82:in `find_user'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/restacker-1.0.0/lib/restacker_config.rb:87:in `find_plane'
/usr/local/lib/ruby/gems/2.5.0/gems/restacker-1.0.0/lib/restacker_config.rb:87:in `[]': no implicit conversion of Symbol into Integer (TypeError)
```

**Comment by alanyee** [comment]
The code itself requires updating the code to the latest version of Ruby. Somewhere, it should be listed that restacker is only compatible to certain version of Ruby ~`2.3.7`
